name: yoji
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^4.3.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  flutter_dotenv: ^5.0.2
  supabase_flutter: ^1.0.0-dev.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
